### ISSUE TITLE
Additional filter params for getStudentDetails

### ISSUE THREAD

**Issue by AbbotsleighGitHub** [TheAlphaSchoolSystemPTYLTD/student-details#14]
It would be helpful if we had additional filter params to choose from e.g. campus, pc_tutor_group, year_group, etc.

**Comment by pmc086** [comment]
In addition to this, filter params for 'date_of_leaving' and 'date_of_entry' would be helpful in order to pull students who have either left or started in the current year (or have a from/to parameter for each so that you can filter between dates) without having to pull the whole list of past or current students.

**Comment by ThisaraP** [comment]
Hi, first of all apologies for the time taken to respond to this query. TASS has now formed a team to communicate in this forum.

Looking at this one, I can see the latest version of this endpoint includes all the fields mentioned in these 2 requests. campus, pc_tutor_group, year_group, date_of_leaving', 'date_of_entry'. If there is no further queries on this, I will mark this issue as resolved.

Thanks
Thisara P
