### ISSUE TITLE
Address Number Values

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/student-details#57]
Hi,

We have been advised by Tammy to ask the question here. We need to map the residential address from Tass API to our Wonde API. Could you please confirm whether in Tass, address number 1 is always correspondence and address number 2 will always be the residential address?

Please let me know if more information is needed.

Thanks

**Comment by tassweb-talon** [comment]
Hi,
In TASS, address number and address name can be configured by customer. Therefore, you might need to consult with each customer on their setup to determine how to map your address.
Cheers

**Comment by igroenewald** [comment]
Hi,
Thank you for the answer. Do you know if Tass has default values for the address numbers and if so, what they are?
Thanks

**Comment by scottetass** [comment]
Hi,

TASS used to setup default address types but in new instances these days it is left completely up to the school to set them up as they see fit. 

For any default ones that _may_ have been setup, although the numbers are not changeable by a school, the descriptions are, so they may have re-purposed the default ones originally created, so we can't guarantee that a number still relates to a particular address type/description.

I did find a few of the default ones as per below but it is not a comprehensive list because as I mentioned, we no longer set up default ones for schools and I dont think a complete list is available anymore.

- 1 - Correspondnce
- 2 - Residential
- 3 - Billing
- 4 - Parent 1
- 5 - Parent 2

Regards, Scott
