### ISSUE TITLE
getCommunicationRulesDetails - Property Names with Trailing Spaces in JSON Responses

### ISSUE THREAD

**Issue by chughson** [TheAlphaSchoolSystemPTYLTD/student-details#59]
Hello,

While reviewing the JSON responses from the `getCommunicationRulesDetails` endpoint, I noticed an inconsistency in the property names. Specifically, the properties "f_deceased_flg " and "m_deceased_flg " contain trailing spaces. 

The Success Response section of the [getCommunicationRulesDetails documentation](https://github.com/TheAlphaSchoolSystemPTYLTD/student-details/blob/master/getCommunicationRulesDetails.md) also shows the "m_deceased_flg ": "N", and "f_deceased_flg ": "N", with the trailing spaces.

This is inconsistent with the property names in the response from the `getParents` endpoint, where the `deceased_flg` property does not include a trailing space. 

Are these trailing spaces intentional, or could they be a slight oversight? 

Cheers.

**Comment by leonseremelis-tass** [comment]
Hi, thank you for your message. 

Yes, this looks like a bug/typo on the deceased_flg fields. I will add this to our backlog and get it fixed up as soon as possible.

**Comment by leonseremelis-tass** [comment]
Following up on this issue for you @chughson. After internal discussion we have decided to leave this as a known issue for now as modifying the property name could break existing partner/client integrations using this endpoint.

**Comment by team-hq** [comment]
I ran into this issue as well. Why don't you guys simply add another attribute without the space, so that you can have both "m_deceased_flg " and "m_deceased_flg"...? It's a really important flag that we've missed for some time now and it caused a quite a bit of destress for the parents. You don't have to decommission the old one. Just make sure that no more people run into this stupid bug.
