### ISSUE TITLE
Using the online-enrolments /getEnrolledStudents.md

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/student-details#68]
Dear Tass Support,

We want to get students with their parents in bulk from the /online-enrolments/getEnrolledStudents end point. How do we do this?

From the Tass documentation Required params are none. How do one pass none params?
If we need to pass the application_id to get students in bulk, where do we get the application_id?

Thank you

**Comment by scottetass** [comment]
Hi,

online-enrolments/getEnrolledStudents is not built for bulk retrieval. One of the conditional parameters has to be provided which restricts the return data to a single student, application or parent.

You could try the student-details/getCommunicationRulesDetails. It retrieves students with their contacts in bulk but the information is limited. 

Example parameters: `{ "commtype": "GEN", "currentstatus": "current" }`

https://github.com/TheAlphaSchoolSystemPTYLTD/student-details/blob/master/getCommunicationRulesDetails.md

Otherwise I can't see anything currently that will achieve what you want to do.

Thanks, Scott

**Comment by igroenewald** [comment]
Hi Scott,

Thank you for the clarification. What does the "application_id" refer to?

Thanks

**Comment by scottetass** [comment]
Hi,

application_id refers to the identifier for the enrolment application. This is a mandatory parameter when the enrolment is created via the api and relates to a single application.

Thanks, Scott
